// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById, getAccessibleProviderConnections,
  getAccessibleProviderConnectionById, canManageProviderConnection,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyByValue, createApiKey, updateApiKey, deleteApiKey, validateApiKey, reserveApiKeyRequest,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, setModelAliasValidated, deleteModelAlias, deleteModelAliasValidated,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  getUsers, getUserById, getUserByUsername, getUserByOidcIdentity,
  getInvitedOidcUserByEmail, createUser, updateUser, bindUserOidcIdentity, migrateUserOidcIssuer, clearUserPassword, deleteUser,
  getConnectionGrants, grantConnection, revokeConnectionGrant, replaceConnectionGrants,
  getConnectionPriorityOverrides, setConnectionPriorityOverride, cleanupConnectionPriorityOverrides, applyPriorityOverrides,
  TOKEN_SAVER_SETTING_KEYS, getUserTokenSaverOverrides, getEffectiveUserTokenSaverSettings, updateUserTokenSaverSettings,
  exportDb, importDb,
} from "@/lib/db/index.js";
